# Generic ble_proxy ESPHome config
# 
# Upload with:
# esphome -s name yourdevicename run ble_proxy_default.yaml
#

substitutions:
  name: default
  <<: !include secrets.yaml

# secrets.yaml definitions:
#   wifi_ssid, wifi_password
#   wifi_hotspot, ota_password

external_components:
  - source:
      type: local
      path: components

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

logger:
# Enable Home Assistant API
api:
  encryption:
    key: "replace-me"
ota:
  - platform: esphome
    password: "replace-me"
esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 1100ms
    window:   1090ms  
bluetooth_proxy:
  active: false  

sensor:
  - platform: esp_now_ble_proxy
    hostname: ${name}
    security_key: "replace-me"
    broadcast_address: "FF:FF:FF:FF:FF:FF"
    notify_interval: 2min
